### ISSUE TITLE
difficulties in downloading the dataset from Google Drive - Need direct link

### ISSUE THREAD

**Issue by jpainam** [layumi/University1652-Baseline#10]
Hi, thank you for sharing your dataset. Living in China, it's almost impossible to download your dataset from Google Drive. It's also stop if we try to use  a VPN. 
Can you provide a direct link to download your dataset?

Thank you

**Comment by layumi** [comment]
Thanks a lot @jpainam 
Is it okay to use OneDrive in China? My colleague say it will be fine.

**Comment by jpainam** [comment]
yes, OneDrive will be fine in China. but https://pan.baidu.com/ is better. You can share any of the two.
Thanks

**Comment by layumi** [comment]
Please send the request via your academic email. I will send the dataset download link to you.

**Comment by jpainam** [comment]
Done. i have sent an email to this email address Zhedong.Zheng@student.uts.edu.au using my academic email
`jpainam@std.uestc.edu.cn
Hope you have received it.

**Comment by jpainam** [comment]
Thanks. the dataset is downloading.
