### ISSUE TITLE
file naming: Error Path too long

### ISSUE THREAD

**Issue by jpainam** [layumi/University1652-Baseline#11]
Hi, I guess on a Unix/Linux system, such error might not occur. But a file naming similar to the Market-1501 dataset could have been better for Windows based systems.
Here an error due to the path length in Windows systems.
![image](https://user-images.githubusercontent.com/1701705/97084024-a794ca00-1646-11eb-861b-a389b3971c86.png)

**Comment by layumi** [comment]
Thanks. This image seems to be collected from Google Image. I directly save the original file name.
