### ISSUE TITLE
How to visualize the retrieved image?

### ISSUE THREAD

**Issue by zkangkang0** [layumi/University1652-Baseline#30]
Hello, I've been looking at your code recently. In test.py file, after extracting the features of the image, save result to pytorch__result. mat file, and then run evaluate_ gpu. py file for evaluation. I want to know how to visualize the search results and get the matching results like Figure 5 in the paper.

**Comment by layumi** [comment]
Hi @zkangkang0 
You may refer to https://github.com/layumi/University1652-Baseline/blob/master/demo.py

**Comment by zkangkang0** [comment]
Thank you very much. My problem has been solved
