### ISSUE TITLE
How to get the GPS information of test/query_drone ?

### ISSUE THREAD

**Issue by xingpingyeyu** [layumi/University1652-Baseline#40]
Thank you very much for your work. I would like to know how to obtain GPS coordinates and other information of test/query_drone. I want to further know the drone images for research.

**Comment by layumi** [comment]
Hi @xingpingyeyu 
Sorry for the late response. 
You also can refer at https://github.com/layumi/University1652-Baseline#news  
<img width="1181" alt="image" src="https://github.com/layumi/University1652-Baseline/assets/8390471/574ec5e1-fda8-460f-90e7-4f5e098aba7a">
