### ISSUE TITLE
Loss and acc validation

### ISSUE THREAD

**Issue by zahraahmadi1996** [layumi/University1652-Baseline#51]
Hello @layumi

Thank you for your valuable work. I have a question regarding the `train.py` file. In the `draw_curve` function, I noticed that the values of `y_err['val']` and `y_loss['val']` are empty. I have checked the code, but I'm unable to find where the validation values are calculated. Could you please guide me on where I can find the calculation of these values and suggest a place where I can print the values to display them in the log?

Thank you!

**Comment by layumi** [comment]
Hi @zahraahmadi1996 
I do not set validation set in this work and dataset. 
Therefore, I disable the validation.
